"""Server configuration loaded from the repository's config.json file."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


CONFIG_PATH = Path(__file__).resolve().parents[1] / "config.json"
DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 8000


@dataclass(frozen=True)
class ServerConfig:
    host: str
    port: int

    @property
    def public_url(self) -> str:
        """Return a useful local URL for links generated by the API."""
        host = "localhost" if self.host in {"0.0.0.0", "::"} else self.host
        if ":" in host and not host.startswith("["):
            host = f"[{host}]"
        return f"http://{host}:{self.port}"


def load_server_config(path: Path = CONFIG_PATH) -> ServerConfig:
    """Load and validate the API bind host and port from *path*.

    Missing configuration keeps the documented defaults so the API remains
    importable when used without the repository checkout.
    """
    if not path.exists():
        return ServerConfig(host=DEFAULT_HOST, port=DEFAULT_PORT)

    try:
        with path.open(encoding="utf-8") as config_file:
            values: Any = json.load(config_file)
    except json.JSONDecodeError as error:
        raise ValueError(f"Invalid JSON in {path}: {error}") from error

    if not isinstance(values, dict):
        raise ValueError(f"{path} must contain a JSON object")

    host = values.get("host", DEFAULT_HOST)
    port = values.get("port", DEFAULT_PORT)

    if not isinstance(host, str) or not host.strip():
        raise ValueError(f"The host in {path} must be a non-empty string")
    if isinstance(port, bool) or not isinstance(port, int) or not 1 <= port <= 65535:
        raise ValueError(f"The port in {path} must be an integer between 1 and 65535")

    return ServerConfig(host=host.strip(), port=port)
